In [1]:
from ossdirectory import fetch_data
from ossdirectory.fetch import OSSDirectory
from typing import List

In [2]:
import pandas as pd

In [3]:
OSSDirectory = fetch_data()
projects: List[dict] = OSSDirectory.projects;
collections: List[dict] = OSSDirectory.collections;

In [4]:
# extract
projects_data = pd.DataFrame(projects)

In [5]:
projects_data['repository_url'] = projects_data['github'].str[0].str.get('url')

In [6]:
projects_data = projects_data[['name', 'description', 'repository_url']]

In [7]:
projects_data

,name,description,repository_url
0,ruler-protocol,NaN,https://github.com/ruler-protocol
1,riftlend,NaN,https://github.com/riftlend
2,rareskills,The longest and hardest blockchain engineering...,https://github.com/rareskills
3,reflexer-labs,NaN,https://github.com/reflexer-labs
4,risedle,Leveraged Position Tokenizing Protocol,https://github.com/risedle
...,...,...,...
6521,world-mini-app-x3x,NaN,NaN
6522,world-mini-app-puf,NaN,NaN
6523,world-mini-app-infofinance-worldpot,NaN,NaN
6524,world-mini-app-tpulsefi,NaN,https://github.com/tradepulse-hub/tpulsefi_newapp
6525,worldcoin,Building the world’s largest identity and fina...,https://github.com/worldcoin

In [8]:
funding_data = pd.read_csv("https://github.com/opensource-observer/oss-funding/blob/main/data/funding_data.csv?raw=true")

In [9]:
funding_data_final = funding_data.merge(projects_data, left_on='to_project_name', right_on='name', how='left')

In [10]:
funding_data_final.dropna(subset=['repository_url'], inplace=True)

In [11]:
funding_data_final.to_csv("../data/proc/project_repos_other_funding.csv", index=False)

In [21]:
matched_data = pd.read_csv("../data/proc/propensity_matched_data.csv")

In [22]:
matched_data

,repo_sha_id,ecosystem,package_name,repository_url,versions_count,first_release_published_at,latest_release_published_at,created_at,updated_at,downloads,dependent_repos_count,dependent_packages_count,stargazers_count,forks_count,average_ranking,treated,record_id,scores,match_id
0,aa0387a5ef2b86ae0e1854086df98fea173b69fc858d30...,conda,typing,https://github.com/python/cpython,7.0,2017-09-11T05:21:36.000Z,2019-07-02T16:39:36.000Z,1664811704657000000,1766952433444000000,NaN,19.263285,51.192993,0.634058,0.271739,17.840519,1,33,0.089803,0
1,2459dc1d0bd7cbfd6a44e80d8b330fdb7cdcae64074fff...,conda,libcurl-static,https://github.com/curl/curl,15.0,2020-07-17T06:29:17.000Z,2022-10-26T09:27:14.000Z,1664811953131000000,1766411652905000000,NaN,34.025455,51.175443,1.182930,1.332668,21.929124,1,107,0.114773,1
2,2459dc1d0bd7cbfd6a44e80d8b330fdb7cdcae64074fff...,maven,com.fpliu.ndk.pkg.prefab.android.21:curl,https://github.com/curl/curl,1.0,2022-04-26T21:10:17.000Z,2022-04-26T21:10:17.000Z,1658775513658000000,1767308752752000000,NaN,31.979944,48.859858,0.583664,0.889842,20.578327,1,108,0.115414,2
3,416eae3d6fa747c5b9b51b667d7364dda44e4ca474d7fd...,spack,fpm,https://github.com/fortran-lang/fpm,10.0,2022-04-05T09:13:49.186Z,2024-01-14T10:11:32.933Z,1649150029160000000,1765126959497000000,NaN,0.000000,57.273864,9.184382,13.199944,19.914548,1,119,0.255738,3
4,6df74e1cfe6e6c9a1aa8b18a24e459c66aca1ee76110db...,go,github.com/rubygems/bundler,https://github.com/rubygems/bundler,149.0,2010-02-04T01:51:46.000Z,2020-01-05T16:46:34.000Z,1680482179150000000,1765271578297000000,NaN,4.758135,9.566350,0.963823,0.513918,3.950556,1,102,0.267197,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,f7abef916801793c6fd7aa4eb98d5c5b07f3d328666cbe...,rubygems,decidim-demographics,https://github.com/decidim/decidim,3.0,2025-09-25T12:27:35.535Z,2025-11-20T08:20:28.933Z,1758803473959000000,1766333711334000000,92.618671,43.647976,14.249420,1.215731,1.279743,30.602308,0,28426,0.857009,88
182,74f8a2794c57006238ac0a24bbb2148f0559d74cf0d5f9...,rubygems,threadsafe,https://github.com/rubygems/rubygems.org,1.0,2018-07-23T03:29:28.638Z,2018-07-23T03:29:28.638Z,1759818582485000000,1765322170895000000,91.740541,0.000000,0.000000,1.019459,0.472432,18.646486,0,15082,0.899889,89
183,34b3652d90698fc55f223e1877b0d6f0e2c42b92d2b79e...,npm,cesium-fork-1.81,https://github.com/CesiumGS/cesium,3.0,2022-10-21T15:28:44.065Z,2023-05-25T02:50:06.514Z,1666374073881000000,1765512636886000000,51.204372,25.305522,16.219767,22.129187,20.515439,27.074857,0,41078,0.911802,90
184,a1bef311751705c42ac4bdd3a7e9d81baf3116b091efaf...,maven,org.http4k:http4k-connect-amazon-containercred...,https://github.com/http4k/http4k,238.0,2022-03-15T16:00:26.000Z,2025-12-30T00:23:35.000Z,1658891718556000000,1767784457713000000,NaN,20.768371,23.154663,39.024097,39.805044,30.688044,0,58615,0.967682,91
185,0caffa4aca4715629d39ae26ffb9e0d4ee7cb0a1cb6915...,maven,io.ebean:ebean-test,https://github.com/ebean-orm/ebean,249.0,2019-07-31T11:34:23.000Z,2025-11-23T09:37:42.000Z,1658998148437000000,1766012754746000000,NaN,1.559935,3.359336,62.832670,58.641409,31.598337,0,66500,0.997113,92